---
- name: Deploy Framework to K8s
  hosts: localhost
  gather_facts: false
  
  # For secure storage of sensitive data
  vars_files:
    - secrets.yml

  # For modular design
  roles:
    - k8s_deploy